# Generated by Django 3.1.3 on 2021-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/cards_jpg')),
                ('card', models.CharField(max_length=3)),
                ('suit', models.CharField(max_length=10)),
            ],
        ),
    ]
