# Generated by Django 3.1.3 on 2021-02-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_image',
            name='image',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
