# Generated by Django 3.1.3 on 2021-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20210202_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_image',
            name='image',
            field=models.ImageField(upload_to='static/cards_jpg2'),
        ),
    ]
